# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ocelotconsulting.com
title: Ocelot Consulting
email: info@ocelotconsulting.com
author: Ocelot Developers
description: > # "Ocelot Consulting specializes in cloud technologies, custom application development and enterprise security.
  Ocelot Consultants are certified AWS Solution Architects and have experience migrating enterprise applications and data for
  Fortune 500 companies.
copyright: 'Copyright &copy; 2018 Ocelot Consulting LLC. All Rights Reserved.'

about: 'Ocelot Consulting specializes in cloud technologies, custom application development and enterprise security.
Ocelot Consultants are certified AWS Solution Architects and have experience migrating enterprise applications and data for
Fortune 500 companies.'
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]
paginate: 5
paginate_path: "/blog/page:num/"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ocelot_llc
  - title: github
    url: https://github.com/ocelotconsulting/
  - title: linkedin
    url: https://www.linkedin.com/company/ocelot-consulting-llc
  - title: facebook
    url: https://facebook.com/ocelotconsultingllc/
  - title: rss
    url: /feed.xml
  - title: slack
    url: http://slack-registration.foxeared.com

# Team names, titles and social links
people:
- name: Tyler Robert
  pic: tyler
  position: Co-Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/tyler-robert
    - title: facebook
      url: http://www.facebook.com/tyler.robert.161
    - title: github
      url: https://github.com/tylerrobert

- name: Larry Anderson
  pic: larry
  position: Co-Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/larryanderson
    - title: github
      url: https://github.com/larryboymi
    - title: stack-overflow
      url: http://stackoverflow.com/users/1380238/larry-anderson

- name: John O'Malley
  pic: john
  position: Co-Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/john-o-malley-9213802
    - title: github
      url: https://github.com/johnomalley
    - title: stack-overflow
      url: http://stackoverflow.com/users/1949840/john-omalley

- name: Chris Coffman
  pic: chris
  position: Co-Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/chris-coffman
    - title: github
      url: https://github.com/theodorick

- name: Patrick Byrne
  pic: patrick
  position: Partner
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/patrickmbyrne/
    - title: github
      url: https://github.com/PMByrne

- name: Derek Tandy
  pic: derek
  position: Partner
  social:
    - title: github
      url: https://github.com/DerekTandy
